# add your custom package feeds here
#
# src/gz example_feed_name http://www.example.com/path/to/files
src/gz avkiller_homeproxy https://homeproxy.avkiller.top
src/gz avkiller_easytier https://easytier-app.avkiller.top